[package]
name = "my_cucumber"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
anyhow = "1"
cucumber = { version = "0.15", features = ["output-junit"] }
tokio = { version = "1.17", features = ["macros", "rt-multi-thread", "time"] }

[[test]]
name = "example"
harness = false