[package]
name = "yace"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
anyhow = "1"
cucumber = { version = "0.19", features = ["output-junit"] }
tokio = { version = "1.24", features = ["macros", "rt-multi-thread", "time"] }

[[test]]
name = "example"
harness = false
