[package]
name = "yace"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
cucumber = { version = "0.20", features = ["output-junit"] }
rand = "0.8.5"
tokio = { version = "1.24", features = ["macros", "rt-multi-thread", "time"] }
